---
abstract: 'delegate testing to the cloud'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  IO::Socket::INET: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-cpantested
recommends:
  App::cpanminus: 0
  App::cpanoutdated: 0
  App::cpantimes: 0
requires:
  CPAN::DistnameInfo: 0
  Carp: 0
  Config: 0
  Data::Dumper: 0
  File::Spec::Functions: 0
  Getopt::Long: 0
  HTTP::Tiny: 0
  IO::Uncompress::Gunzip: 0
  JSON::PP: 0
  Pod::Usage: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/creaktive/App-cpantested/issues
  homepage: https://github.com/creaktive/App-cpantested
  repository: git://github.com/creaktive/App-cpantested.git
version: 0.001
